name: Solana Container Build

on:
  schedule:
    # Cron format: minute hour day-of-month month day-of-week
    # ┌───────── minute (0-59)
    # │ ┌─────── hour (0-23)
    # │ │ ┌───── day of month (1-31)
    # │ │ │ ┌─── month (1-12 or JAN-DEC)
    # │ │ │ │ ┌─ day of week (0-6 or SUN-SAT)
    # │ │ │ │ │
    # 0 2 * * 4    Run every Thursday at 02:00 UTC
    - cron: '0 2 * * 4'
  # Optional: Allow manual triggering
  workflow_dispatch:

jobs:
  builder:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          PLATFORM: ${{ matrix.platform }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          PLATFORM: ${{ matrix.platform }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build builder stage
        run: make build-builder
        env:
          CI: true
          DOCKER_BUILDKIT: 1
          PLATFORM: ${{ matrix.platform }}
          CONTAINER_REGISTRY: ghcr.io/${{ github.repository }}

  runtime:
    needs: builder
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
        distro:
          - { name: debian, release: bullseye, variant: slim }
          - { name: debian, release: bullseye, variant: "" }
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          PLATFORM: ${{ matrix.platform }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          PLATFORM: ${{ matrix.platform }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build runtime
        run: make build-runtime
        env:
          CI: true
          DOCKER_BUILDKIT: 1
          PLATFORM: ${{ matrix.platform }}
          CONTAINER_REGISTRY: ghcr.io/${{ github.repository }}
          DISTRO: ${{ matrix.distro.name }}
          DISTRO_RELEASE: ${{ matrix.distro.release }}
          DISTRO_VARIANT: ${{ matrix.distro.variant }}

  cleanup:
    needs: [runtime]
    runs-on: ubuntu-latest
    steps:
      - name: Delete old container images
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'solana-containers'
          package-type: 'container'
          min-versions-to-keep: 5
          delete-only-untagged-versions: 'true'