name: Solana Container Build

on:
  schedule:
    # Cron format: minute hour day-of-month month day-of-week
    # ┌───────── minute (0-59)
    # │ ┌─────── hour (0-23)
    # │ │ ┌───── day of month (1-31)
    # │ │ │ ┌─── month (1-12 or JAN-DEC)
    # │ │ │ │ ┌─ day of week (0-6 or SUN-SAT)
    # │ │ │ │ │
    # 0 7 1 * *    Run on the 1st day of every month at 02:00 EST (07:00 UTC)
    - cron: '0 7 1 * *'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            runs-on: ubuntu-latest
          - platform: linux/arm64
            runs-on: self-hosted-linux-arm64
        distro:
          - name: debian
            release: bullseye
            variant: slim
          - name: debian
            release: bullseye
            variant: ""
      fail-fast: false
    name: build (${{ matrix.platform }}, ${{ matrix.distro.name }}, ${{ matrix.distro.release }}${{ matrix.distro.variant && format(', {0}', matrix.distro.variant) }})
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/build-platform
        with:
          platform: ${{ matrix.platform }}
          distro: ${{ matrix.distro.name }}
          distro_release: ${{ matrix.distro.release }}
          distro_variant: ${{ matrix.distro.variant }}
          token: ${{ secrets.GITHUB_TOKEN }}

  cleanup:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Delete old container images
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'solana-containers'
          package-type: 'container'
          min-versions-to-keep: 5
          delete-only-untagged-versions: 'true'